#!/bin/bash
if whoami | grep -q root; then
	echo Cannot run this script as root
	exit
fi
if ! cd ~/.local/bin/quickemu; then
	echo Quickemu not found in expected directory. Run quickemu-create to fix the issue.
	exit
fi
if ! cd ~/Documents/VMs; then
	mkdir ~/Documents/VMs
	echo Created VMs folder.
fi
export PATH=$PATH:~/.local/bin/quickemu
IFS=$'\n' VMs=( $(ls ~/Documents/VMs) )
echo $VMs
cd ~/Documents/VMs
if [ -z $VMs ]; then
    echo No VMs found. Run quickemu-create to create one.
    exit
fi
echo Available VMs:
for i in "${!VMs[@]}"; do
	echo "$((i+1)). ${VMs[$i]}"
done
read -p 'Select a VM: ' selection
cd ~/Documents/VMs/"${VMs[$selection-1]}"
quickemu --vm $(ls | grep .conf)
echo quickemu --vm $(ls | grep .conf)